files:
  - 
    source: '/gemini/**/values/*.xml'
    ignore:
      - '/*_stable/'
    translation: '/gemini/**/values-%two_letters_code%/%original_file_name%'
    update_option: update_as_unapproved
